### ISSUE TITLE
orchard 1.9.2 doesn't work with MySQL community edition 5.7.10

### ISSUE THREAD

**Issue by TiddlyRunner** [OrchardCMS/Orchard#6197]
I downloaded orchard 1.9.2 zip, and followed the steps(http://docs.orchardproject.net/Documentation/Manually-installing-Orchard-zip-file) , I used MySQL community edition 5.7.10, connection string is Data Source=localhost;Database=mydb;User Id=root;Password=123456 . After the setup page, I got 404 errors, and the log looked like this:

> 2015-12-17 13:50:33,000 [26] Orchard.Data.Migration.DataMigrationManager - Default - Error while running migration version 0 for Orchard.Autoroute.
> http://localhost:8080/ System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> MySql.Data.MySqlClient.MySqlException: BLOB/TEXT column 'DisplayAlias' used in key specification without a key length
> at MySql.Data.MySqlClient.MySqlStream.ReadPacket()
> at MySql.Data.MySqlClient.NativeDriver.GetResult(Int32& affectedRow, Int32& insertedId)
> at MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
> at MySql.Data.MySqlClient.MySqlDataReader.NextResult()
> at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
> at MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery()
> at Orchard.Data.Migration.Interpreters.DefaultDataMigrationInterpreter.RunPendingStatements() in z:\Builds\work\9f6cd39ff0f68f41\src\Orchard\Data\Migration\Interpreters\DefaultDataMigrationInterpreter.cs:line 337
> at Orchard.Data.Migration.Interpreters.DefaultDataMigrationInterpreter.Visit(AlterTableCommand command) in z:\Builds\work\9f6cd39ff0f68f41\src\Orchard\Data\Migration\Interpreters\DefaultDataMigrationInterpreter.cs:line 144
> at Orchard.Data.Migration.Schema.SchemaBuilder.AlterTable(String name, Action`1 table) in z:\Builds\work\9f6cd39ff0f68f41\src\Orchard\Data\Migration\Schema\SchemaBuilder.cs:line 51
> at Orchard.Autoroute.Migrations.Create()
> --- End of inner exception stack trace ---
> at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
> at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
> at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
> at Orchard.Data.Migration.DataMigrationManager.Update(String feature) in z:\Builds\work\9f6cd39ff0f68f41\src\Orchard\Data\Migration\DataMigrationManager.cs:line 115

then I deleted App_Data and started over and used SQL Server, then everything is OK.

**Comment by Thierry-S** [comment]
I get the same error "Setup failed: Error while running migration version 0 for Orchard.Autoroute" with the zip downloaded from http://orchardproject.net/download which points to https://github.com/OrchardCMS/Orchard/releases/download/1.10/Orchard.Web.zip

Could be the same or similar to: MySql AutoRoute Migrations CreateIndex Issue #4556 which was fixed in Aug 2015 apparently in 1.9.

**Comment by Rathje** [comment]
Hi,
The exact same problem still exist with version 1.10.1 and MySql 5.6 or 5.7.
I have followed the guidences to tweek TEXT columns etc, but with no luck...
It's therefore impossible to implement with MySql for me. Is this something you're working on to solve in next version or will it be finally solved in the Orchard 2 project?
Best regards
Lars, Denmark

**Comment by ramiassi** [comment]
I could solve this problem by modifying the migrations.cs file in three modules (Autoroute, MediaLibrary, Recipes) like this:

Orchard version 1.10.1

Orchard.Autoroute/Migrations.cs:

line 23:  .CreateIndex("IDX_AutoroutePartRecord_DisplayAlias", "DisplayAlias(767)")
line 38:   .CreateIndex("IDX_AutoroutePartRecord_DisplayAlias", "DisplayAlias(767)")

Orchard.MediaLibrary/Migrations.cs:

line 20:   .CreateIndex("IDX_MediaPartRecord_FolderPath", "FolderPath(767)")
line 167: .CreateIndex("IDX_MediaPartRecord_FolderPath", "FolderPath(767)")

Orchard.Recipes/Migrations.cs:

line 19:  table.CreateIndex("IDX_RecipeStepResultRecord_ExecutionId_StepName", "ExecutionId", "StepName(767)");

I wish the orchard team could add these modifications to the next release.

Regards...

**Comment by Thomas-Clark** [comment]
You can also enable the innodb_large_prefix option in MySQL and you need not make the migration changes.

**Comment by macintyres** [comment]
hmmm. I have large prefix enabled, but I get the same error.

**Comment by sebastienros** [comment]
@siyamandayubi has done some work recently on the dev branch to make it work again. Not sure if it has been back-ported to 1.10.x already. If not you can always help on this if you want, there is a PR that should contain all the necessary changes.

**Comment by sebastienros** [comment]
Fixed in https://github.com/OrchardCMS/Orchard/pull/7607

**Comment by robert-smith-docobo** [comment]
I have just tested with 1.10.2 and I get a MySQL exception relating to key length, when trying to set up Orchard with MySQL.  The exception is:

    "Specified key was too long; max key length is 767 bytes"

The SQL being executed is 

   CREATE INDEX `IDX_AutoroutePartRecord_DisplayAlias` ON `Orchard_Autoroute_AutoroutePartRecord` (DisplayAlias(767)) 

I also tested with the latest version of the code base available on GitHub (#7602) and observed the same problem.

**Comment by robert-smith-docobo** [comment]
I just a bit of investigation and think I may have an idea where the problem is.  What I found is that if I change the SQL query to the following, then I do not get the error:

   CREATE INDEX `IDX_AutoroutePartRecord_DisplayAlias` ON `Orchard_Autoroute_AutoroutePartRecord` (DisplayAlias(255)) 

What I suspect is that the character coding means the effective size limit on the key is 255 characters because of a multiply by 3 due to utf8 character coding.  Hence, I think (but have not tried) changing the constant 767 to 255 in the method CreateStatements(..) start at line 88 in the file src\Orchard\Data\Migration\Interpreters\MySqlCommandInterpreter.cs may help (line 97 and 107).  Also, it may be necessary to used a scaled version of the constant CHARACTER_MAXIMUM_LENGTH on line 97.

**Comment by robert-smith-docobo** [comment]
An update, I found that the problem is resolved if line 107 in src\Orchard\Data\Migration\Interpreters\MySqlCommandInterpreter.cs is changed from:
  
     columnList[columnList.IndexOf(columnName)] = string.Format("{0}(767)", columnName);

to:
     columnList[columnList.IndexOf(columnName)] = string.Format("{0}(255)", columnName);

This seems to have allowed me to get around my immediate problem and set up Orchard with MySQL.  However, I am not familiar with the code / schema and so am unsure of what unintended side-affects this may have.

**Comment by siyamandayubi** [comment]
Hi all & sorry for late answer.

I just downloaded Orchard 10.2, and tested on Mysql db with the engine innodb_version	5.7.10. I didn't get that exception and every things works fine except for another error I mentioned later.

I also tested it with different Collation (Default server and utf8-general_ci). @robert-smith-docobo can you please provide more information about the database version & engine?

Apparently I found another problem?
In version 10.2, for the following Command,

    ```
    public void CreateSchema() {
            _schemaBuilder.CreateTable(TableName, table => table
                .Column<int>("Id", column => column.PrimaryKey().Identity())
                .Column<string>("Name", column => column.NotNull().WithLength(512).Unique())
                .Column<string>("MachineName", column => column.WithLength(256))
                .Column<DateTime>("CreatedUtc")
                .Column<DateTime>("ValidUntilUtc", column => column.Nullable()));

            _schemaBuilder.AlterTable(TableName, table => {
                table.CreateIndex("IDX_DistributedLockRecord_Name", "Name");
            });
        }
```
Orchard generates the following SQL,

create table `Orchard_Framework_DistributedLockRecord` (`Id` INTEGER NOT NULL AUTO_INCREMENT, `Name` TEXT not null unique, `MachineName` TEXT, `CreatedUtc` DATETIME, `ValidUntilUtc` DATETIME, primary key ( `Id` ) )

which causes a non-blocking exception, because Name field no longer has a length limit.
@sebastienros Should I create a new Issue for that? And also, we fixed the issue for create index command, but we should think about unique constraint as well.
