### ISSUE TITLE
Dynamic Forms not working with 1.9.2 zip distribution

### ISSUE THREAD

**Issue by sfmskywalker** [OrchardCMS/Orchard#6260]
See the discussion here: http://orchard.codeplex.com/discussions/649349

**Complaint**
Cannot create new Form content item / Forms element category does not appear in the toolbox (of the Layout editor).

**Comment by sebastienros** [comment]
I could repro with the online package, but can't explain why. Logs are empty. It looks like the migration are not running, like no code from this module is running.
I tried with a PreCompiled version of 1.9.3 and it worked fine. So the issue will be fixed as we ship it.

**Comment by moonica** [comment]
This appears to be happening in at least 1.93, 1.10.0 and 1.10.1 - I've tried all three and can not get Dynamic Forms module to be pulled into the menu.

**Comment by sfmskywalker** [comment]
I just tried the 1.10.1 zip file, and was not able to reproduce the issue. In other words, it just works. This is what I did:

1. Download the 1.10.1 Orchard.Web.zip package from here: https://github.com/OrchardCMS/Orchard/releases/download/1.10.1/Orchard.Web.zip
2. Right-click on the zip file, check "Unblock" and hit OK. I don't know if this is really necessary, but I do it just in case.
3. Unzip the file.
4. Open the directory with Visual Studio using the "Open -> Web Site" menu item.
5. Right-click on the Orchard root project node and click "View in Browser (Google Chrome)"
6. The setup screen appears. Selected the Default recipe and hit Setup.
7. Navigate to the dashboard -> Modules and enable the Dynamic Form features.
8. The New -> Form menu item appears.

Perhaps you could describe your steps in detail, or even better: create a screencast?

**Comment by moonica** [comment]
Hi Sipke,
Thanks for the response.

I followed the instructions here:
http://docs.orchardproject.net/en/latest/Documentation/Manually-installing-Orchard-zip-file/

I downloaded the zip file, extracted the contents, then created a new site in IIS pointing to the Orchard folder in the extracted location. I fixed the app pool identity and permissions on the Media, App_Data, Modules and Themes folders. Then I ran and set up the site (pointing at a new db on my local instance of SQL Server for the data). The site works fine but I can't access forms.

I will try your steps, thanks again.

Screenshot from v1.10.1
![noforms](https://cloud.githubusercontent.com/assets/4337922/16521991/fc74983e-3f9a-11e6-9fa1-0926a33d3229.jpg)

**Comment by moonica** [comment]
Tried to follow the steps given. I did make the following change to your step 4:
Opened <unzipped file>/Orchard-1.10.1/**src/Orchard.Web** as a website.

Encountered the following error on build. Nuget package manager reports I have 5.2.3 installed, although when I include pre-releases in my search I can only find reference to 5.2.2 or 5.2.3-beta1.

Error
Could not load file or assembly 'System.Web.Mvc, Version=5.2.3, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. 
The system cannot find the file specified.		
<path>\Orchard-1.10.1\src\Orchard.Web\Web.config	line 55	

I'll try installing 1.9.3 in the same way when I get home, see how I get on with that.

![image](https://cloud.githubusercontent.com/assets/4337922/16523086/dd03590c-3fa1-11e6-9cdf-ddbf19648cde.png)

**Comment by sfmskywalker** [comment]
I'm not sure you should open Orchard as a website if you have the source code on your machine. In that case, you should simply open the Orchard.sln file. That should build just fine.

**Comment by sfmskywalker** [comment]
I tried your steps with a local IIS server, but was still unable to reproduce the issue. Can you confirm that the **Orchard.DynamicForms.dll** exists in the following folders?

- App_Data/Dependencies
- Modules/Orchard.DynamicForms/bin

**Comment by moonica** [comment]
Note that I did not have the source code for the latest versions on my machine before trying it that way today, although I did have the source for 1.8 elsewhere. I do not have a sln file for later versions, not until after I followed the suggested steps above and saved it as a VS solution so as to check the version of the MVC dll with Nuget when it wouldn't run.

The DynamicForms dll did not exist in App_Data/Dependencies. I tried adding it, but with no success.

**Comment by sfmskywalker** [comment]
Oh ok, then the **src** in your path tripped me off. If you don't have the source code, then you should not try and build it in VS. Just run it in the browser as per my point 5.

**Comment by UsamaTahir1** [comment]
@sfmskywalker Is there any solution for this issue? I'm using 1.9.2 version, I deployed the complied code for orchard on Azure web app, created a new default tenant, and when I enabled the DynamicForms module, it got enabled but its migration did not run, admin menu item for 'Form Submissions' did not appear, seems like all the code for the module is not running. Please help me out if you have any suggestion.

**Comment by sfmskywalker** [comment]
Can you check App_Data/Dependencies and see if it contains the Orchard.DynamicForms.dll file? If not, try and copy it from Modules/Orchard.DynamicForms into that folder and try again.

**Comment by sfmskywalker** [comment]
I assume this SO post is yours as well? --> https://stackoverflow.com/questions/45457863/orchard-dynamicforms-module-is-enabled-but-code-not-workin

**Comment by Niels-V** [comment]
Out of nowhere I have this same issue on a live 1.92.2 instance (which worked before). I still didn't resolve the issue, looking for clues (tried uploading the assembly to app_data/dependencies without success).

I raised the errorlevel to all, and got these in my log, complaining about a missing Orchard.Layouts assembly:
```
2017-08-15 20:40:30,823 [10] Orchard.Environment.Extensions.Loaders.DynamicExtensionLoader - (null) - Start loading dynamic extension "Dynamic Forms"
 (null)
2017-08-15 20:40:30,854 [10] Orchard.Environment.DefaultBuildManager - (null) - Error when compiling assembly under ~/Modules/Orchard.DynamicForms/Orchard.DynamicForms.csproj.
 (null)
System.Configuration.ConfigurationErrorsException: Could not load file or assembly 'Orchard.Layouts' or one of its dependencies. The system cannot find the file specified. (D:\home\site\wwwroot\modules\orchard.dynamicforms\web.config line 36) ---> System.IO.FileNotFoundException: Could not load file or assembly 'Orchard.Layouts' or one of its dependencies. The system cannot find the file specified.
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean forIntrospection)
   at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, Boolean forIntrospection)
   at System.Reflection.Assembly.Load(String assemblyString)
   at System.Web.Configuration.CompilationSection.LoadAssemblyHelper(String assemblyName, Boolean starDirective)
   --- End of inner exception stack trace ---
   at System.Web.Configuration.CompilationSection.LoadAssemblyHelper(String assemblyName, Boolean starDirective)
   at System.Web.Configuration.CompilationSection.LoadAssembly(AssemblyInfo ai)
   at System.Web.Compilation.BuildManager.GetReferencedAssemblies(CompilationSection compConfig)
   at System.Web.Compilation.WebDirectoryBatchCompiler..ctor(VirtualDirectory vdir)
   at System.Web.Compilation.BuildManager.BatchCompileWebDirectoryInternal(VirtualDirectory vdir, Boolean ignoreErrors)
   at System.Web.Compilation.BuildManager.CompileWebFile(VirtualPath virtualPath)
   at System.Web.Compilation.BuildManager.GetVPathBuildResultInternal(VirtualPath virtualPath, Boolean noBuild, Boolean allowCrossApp, Boolean allowBuildInPrecompile, Boolean throwIfNotFound, Boolean ensureIsUpToDate)
   at System.Web.Compilation.BuildManager.GetVPathBuildResultWithNoAssert(HttpContext context, VirtualPath virtualPath, Boolean noBuild, Boolean allowCrossApp, Boolean allowBuildInPrecompile, Boolean throwIfNotFound, Boolean ensureIsUpToDate)
   at System.Web.Compilation.BuildManager.GetVPathBuildResult(HttpContext context, VirtualPath virtualPath, Boolean noBuild, Boolean allowCrossApp, Boolean allowBuildInPrecompile, Boolean ensureIsUpToDate)
   at System.Web.Compilation.BuildManager.GetCompiledAssembly(String virtualPath)
   at Orchard.Environment.DefaultBuildManager.GetCompiledAssembly(String virtualPath) in c:\Data\OrchardSource\src\Orchard\Environment\IBuildManager.cs:line 53
2017-08-15 20:40:31,119 [10] Orchard.Environment.Extensions.ExtensionManager - (null) - No suitable loader found for extension "Orchard.DynamicForms"
 (null)
```

I tried to solve this to put the Orchards.Layouts.dll assembly into the dependencies folder as well, but this gives another error:
```
2017-08-15 20:53:54,546 [8] Orchard.FileSystems.Dependencies.DynamicModuleVirtualPathProvider - (null) - GetFileHash("/Modules/Orchard.DynamicForms/Orchard.DynamicForms.csproj"): a09ba9750d77a37f
 (null)
2017-08-15 20:53:54,546 [8] Orchard.Environment.DefaultBuildManager - (null) - Error when compiling assembly under ~/Modules/Orchard.DynamicForms/Orchard.DynamicForms.csproj.
 (null)
System.Web.HttpCompileException (0x80004005): d:\home\site\wwwroot\Modules\Orchard.DynamicForms\Drivers\UserNameFieldElementDriver.cs(5): error CS0433: The type 'Orchard.Layouts.Framework.Drivers.ElementDriver<TElement>' exists in both 'd:\home\site\wwwroot\App_Data\Dependencies\Orchard.Layouts.dll' and 'd:\local\Temporary ASP.NET Files\root\ca0adc57\440e2316\App_Web_blvrvhwk.dll'
   at System.Web.Compilation.AssemblyBuilder.Compile()
   at System.Web.Compilation.BuildProvidersCompiler.PerformBuild()
   at System.Web.Compilation.BuildManager.CompileWebFile(VirtualPath virtualPath)
   at System.Web.Compilation.BuildManager.GetVPathBuildResultInternal(VirtualPath virtualPath, Boolean noBuild, Boolean allowCrossApp, Boolean allowBuildInPrecompile, Boolean throwIfNotFound, Boolean ensureIsUpToDate)
   at System.Web.Compilation.BuildManager.GetVPathBuildResultWithNoAssert(HttpContext context, VirtualPath virtualPath, Boolean noBuild, Boolean allowCrossApp, Boolean allowBuildInPrecompile, Boolean throwIfNotFound, Boolean ensureIsUpToDate)
   at System.Web.Compilation.BuildManager.GetVPathBuildResult(HttpContext context, VirtualPath virtualPath, Boolean noBuild, Boolean allowCrossApp, Boolean allowBuildInPrecompile, Boolean ensureIsUpToDate)
   at System.Web.Compilation.BuildManager.GetCompiledAssembly(String virtualPath)
   at Orchard.Environment.DefaultBuildManager.GetCompiledAssembly(String virtualPath) in c:\Data\OrchardSource\src\Orchard\Environment\IBuildManager.cs:line 53
2017-08-15 20:53:54,828 [8] Orchard.Environment.Extensions.ExtensionManager - (null) - No suitable loader found for extension "Orchard.DynamicForms"
```

I'm giving up for now, I hope someone can give me a clue here.

**Comment by UsamaTahir1** [comment]
@Niels-V  Issue is being produced due to Dynamic Extension Loader of orchard cms. There are a couple of extension loaders in orchards. PrecompiledExtension Loader and Dynamic Extension Loader. You can find the relevant information on Orchardproject documentations.
What we did as a quick fix is to disable the dynamic extension loader and let the Precompiled Extension loader do the work.

**Comment by sebastienros** [comment]
And I assume this was fixed with more recent releases

**Comment by tgolla** [comment]
The issue has also appeared for me in the compiled 1.10.2 zip file.   Update: Turning off Dynamic Extension Loader and it did not resolver the issue (http://docs.orchardproject.net/en/latest/Documentation/Orchard-module-loader-and-dynamic-compilation/).  Pulling the latest 1.10.2 source, did a 'build precompiled' and using that code did resolved the issue.

**Comment by sebastienros** [comment]
Assigning to 1.10.3 to ensure it doesn't happen with the next package.

**Comment by BenedekFarkas** [comment]
No repro with Precompiled package built on 1.10.x.

**Comment by danmincu** [comment]
> The issue has also appeared for me in the compiled 1.10.2 zip file. Update: Turning off Dynamic Extension Loader and it did not resolver the issue (http://docs.orchardproject.net/en/latest/Documentation/Orchard-module-loader-and-dynamic-compilation/). Pulling the latest 1.10.2 source, did a 'build precompiled' and using that code did resolved the issue.

Confirming this ^^ fixed the issue however I had to manually add `Orchard.Roles` and `Orchard.Layout` projects to Orchard.Web otherwise I wasn't able to publish with the `build precompiled` option.

```
Severity	Code	Description	Project	File	Line	Suppression State
Error		Could not load file or assembly 'Orchard.Roles, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.	Orchard.Web	E:\GitHub\Orchard\src\Orchard.Web\obj\Release\AspnetCompileMerge\Source\modules\orchard.openid\web.config	41	

```
